CREATE TABLE "venue_halls" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "venue_halls_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"venue_id" integer NOT NULL,
	"name" text NOT NULL,
	"ph" text DEFAULT 'v2' NOT NULL,
	"type" text NOT NULL,
	"area" text NOT NULL,
	"theatre" integer DEFAULT 0 NOT NULL,
	"floating" integer DEFAULT 0 NOT NULL,
	"dining" integer DEFAULT 0 NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "venue_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "venue_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"venue_id" integer NOT NULL,
	"url" text NOT NULL,
	"alt" text DEFAULT '' NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "venues" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "venues_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"city_slug" text DEFAULT 'nagpur' NOT NULL,
	"locality" text NOT NULL,
	"address" text NOT NULL,
	"type" text NOT NULL,
	"type_slug" text NOT NULL,
	"capacity_min" integer DEFAULT 0 NOT NULL,
	"capacity_max" integer DEFAULT 0 NOT NULL,
	"veg_plate" integer DEFAULT 0 NOT NULL,
	"nv_plate" integer DEFAULT 0 NOT NULL,
	"hall_rent" integer DEFAULT 0 NOT NULL,
	"min_guarantee" integer DEFAULT 0 NOT NULL,
	"rating" numeric(3, 1) DEFAULT '0' NOT NULL,
	"reviews" integer DEFAULT 0 NOT NULL,
	"bookings_month" integer DEFAULT 0 NOT NULL,
	"tag" text DEFAULT '' NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"ph" text DEFAULT 'v2' NOT NULL,
	"scene" text DEFAULT '' NOT NULL,
	"amenities" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"is_signature" boolean DEFAULT false NOT NULL,
	"parking" integer DEFAULT 0 NOT NULL,
	"rooms" integer,
	"owner_user_id" text,
	"contact_name" text,
	"contact_phone" text,
	"contact_email" text,
	"whatsapp" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"meta" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "venues_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "vendor_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendor_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vendor_id" integer NOT NULL,
	"url" text NOT NULL,
	"alt" text DEFAULT '' NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vendors" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vendors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"category" text NOT NULL,
	"category_slug" text NOT NULL,
	"name" text NOT NULL,
	"city" text NOT NULL,
	"locality" text NOT NULL,
	"rating" numeric(3, 1) DEFAULT '0' NOT NULL,
	"reviews" integer DEFAULT 0 NOT NULL,
	"price_from" integer DEFAULT 0 NOT NULL,
	"completed" integer DEFAULT 0 NOT NULL,
	"years_exp" integer DEFAULT 0 NOT NULL,
	"ph" text DEFAULT 'v2' NOT NULL,
	"scene" text DEFAULT '' NOT NULL,
	"tagline" text DEFAULT '' NOT NULL,
	"description" text,
	"owner_user_id" text,
	"contact_name" text,
	"contact_phone" text,
	"contact_email" text,
	"whatsapp" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "vendors_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "getaway_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "getaway_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"getaway_id" integer NOT NULL,
	"url" text NOT NULL,
	"alt" text DEFAULT '' NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "getaways" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "getaways_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"location" text NOT NULL,
	"hours_from_nagpur" text NOT NULL,
	"beds" integer DEFAULT 0 NOT NULL,
	"guests" integer DEFAULT 0 NOT NULL,
	"weekday" integer DEFAULT 0 NOT NULL,
	"weekend" integer DEFAULT 0 NOT NULL,
	"rating" numeric(3, 1) DEFAULT '0' NOT NULL,
	"reviews" integer DEFAULT 0 NOT NULL,
	"ph" text DEFAULT 'v2' NOT NULL,
	"scene" text DEFAULT '' NOT NULL,
	"tagline" text DEFAULT '' NOT NULL,
	"description" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "getaways_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "destinations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "destinations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"city" text NOT NULL,
	"tag" text NOT NULL,
	"ph" text DEFAULT 'v2' NOT NULL,
	"venues" integer DEFAULT 0 NOT NULL,
	"price_from" text DEFAULT '' NOT NULL,
	"feat" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "destinations_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "real_wedding_images" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "real_wedding_images_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"real_wedding_id" integer NOT NULL,
	"url" text NOT NULL,
	"alt" text DEFAULT '' NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "real_weddings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "real_weddings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"couple" text NOT NULL,
	"venue" text NOT NULL,
	"date" text NOT NULL,
	"guests" integer DEFAULT 0 NOT NULL,
	"ph" text DEFAULT 'v2' NOT NULL,
	"scene" text DEFAULT '' NOT NULL,
	"quote" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "real_weddings_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "enquiries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "enquiries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"user_id" text,
	"kind" text NOT NULL,
	"venue_slug" text,
	"vendor_slug" text,
	"getaway_slug" text,
	"category" text,
	"name" text,
	"phone" text,
	"email" text,
	"event_date" text,
	"guest_count" text,
	"message" text,
	"source_url" text,
	"user_agent" text,
	"status" text DEFAULT 'new' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "listing_application_media" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "listing_application_media_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"application_id" integer NOT NULL,
	"data" text NOT NULL,
	"mime_type" text NOT NULL,
	"file_name" text,
	"type" text DEFAULT 'image' NOT NULL,
	"order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "listing_applications" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "listing_applications_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"user_id" text,
	"listing_type" text,
	"business_name" text NOT NULL,
	"business_type" text NOT NULL,
	"category" text,
	"contact_name" text NOT NULL,
	"phone" text NOT NULL,
	"email" text NOT NULL,
	"city" text NOT NULL,
	"locality" text DEFAULT '' NOT NULL,
	"website" text,
	"message" text,
	"details" jsonb,
	"amenities" jsonb,
	"status" text DEFAULT 'pending' NOT NULL,
	"rejection_note" text
);
--> statement-breakpoint
CREATE TABLE "newsletter_signups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "newsletter_signups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"email" text NOT NULL,
	"source" text,
	CONSTRAINT "newsletter_signups_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "profiles" (
	"user_id" text PRIMARY KEY NOT NULL,
	"role" text DEFAULT 'customer' NOT NULL,
	"phone" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "saved_listings" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"type" text NOT NULL,
	"slug" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "site_config" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text DEFAULT 'true' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now(),
	"updated_by" text
);
--> statement-breakpoint
CREATE TABLE "cities" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"lat" double precision NOT NULL,
	"lng" double precision NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "cities_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "venue_halls" ADD CONSTRAINT "venue_halls_venue_id_venues_id_fk" FOREIGN KEY ("venue_id") REFERENCES "public"."venues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "venue_images" ADD CONSTRAINT "venue_images_venue_id_venues_id_fk" FOREIGN KEY ("venue_id") REFERENCES "public"."venues"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vendor_images" ADD CONSTRAINT "vendor_images_vendor_id_vendors_id_fk" FOREIGN KEY ("vendor_id") REFERENCES "public"."vendors"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "getaway_images" ADD CONSTRAINT "getaway_images_getaway_id_getaways_id_fk" FOREIGN KEY ("getaway_id") REFERENCES "public"."getaways"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "real_wedding_images" ADD CONSTRAINT "real_wedding_images_real_wedding_id_real_weddings_id_fk" FOREIGN KEY ("real_wedding_id") REFERENCES "public"."real_weddings"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "listing_application_media" ADD CONSTRAINT "listing_application_media_application_id_listing_applications_id_fk" FOREIGN KEY ("application_id") REFERENCES "public"."listing_applications"("id") ON DELETE cascade ON UPDATE no action;